/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "assemble_game.baml": "// BAML schema for the local LFM2.5-VL-450M-Extract engine driving the\n// `AgentLoop`. The engine drives tool calls until it emits a `final` message\n// or the loop budget is exhausted. Constraints are typed at the BAML layer:\n// the `AssembleGameResponse` discriminated union guarantees the caller\n// receives either a `tool-call` envelope or a `final` message.\n\nclass AgentMessage {\n  role \"system\" | \"user\" | \"assistant\" | \"tool\"\n  content string\n  tool_call_id string?\n  tool_name string?\n}\n\nclass AgentToolDescriptor {\n  tool_name string\n  display_name string\n  description string\n  arguments_schema string\n  capability_tags string[]\n}\n\nclass AgentToolCall {\n  call_id string\n  tool_name string\n  arguments string\n}\n\nclass AssembleGameRequest {\n  system_prompt string\n  messages AgentMessage[]\n  tools AgentToolDescriptor[]\n  max_steps int\n  temperature float\n}\n\nclass AssembleGameResponse {\n  kind \"tool-call\" | \"final\"\n  message string?\n  tool_call AgentToolCall?\n}\n\nfunction AssembleGame(request: AssembleGameRequest) -> AssembleGameResponse {\n  client LocalOllamaLfmExtract\n  prompt #\"\n    {{ request.system_prompt }}\n\n    {% for message in request.messages %}\n    {{ message.role }}: {{ message.content }}\n    {% endfor %}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
  "clients.baml": "// BAML client configurations. The local client targets the on-device Ollama\n// instance running the LFM2.5-VL-450M-Extract model (wired from the\n// Moonshine Streaming CPU config). The paid client targets the hosted OpenRouter\n// router for the user-triggered \"Paid Online Assembly\" action.\n//\n// Both clients are configured via environment variables:\n//   PLAYCRAFT_OLLAMA_URL (default: http://127.0.0.1:11434)\n//   PLAYCRAFT_OLLAMA_MODEL (default: lfm2.5-vl-450m-extract)\n//   PLAYCRAFT_OPENROUTER_API_KEY (required for paid)\n//   PLAYCRAFT_OPENROUTER_MODEL (default: liquid/lfm-2.5-450m)\n\nclient<llm> LocalOllamaLfmExtract {\n  provider ollama\n  options {\n    base_url env.PLAYCRAFT_OLLAMA_URL \"http://127.0.0.1:11434\"\n    model env.PLAYCRAFT_OLLAMA_MODEL \"lfm2.5-vl-450m-extract\"\n  }\n}\n\nclient<llm> PaidOpenRouterLfm {\n  provider openai-generic\n  options {\n    base_url \"https://openrouter.ai/api/v1\"\n    api_key env.PLAYCRAFT_OPENROUTER_API_KEY\n    model env.PLAYCRAFT_OPENROUTER_MODEL \"liquid/lfm-2.5-450m\"\n  }\n}\n",
  "generators.baml": "generator target {\n  output_type typescript\n  output_dir \"../packages/core/baml_client\"\n  version \"0.223.0\"\n  // The generated client uses // @ts-nocheck and bare relative imports.\n  // This is a BAML convention; the generated code is excluded from the\n  // project's guardrail scans. The bridge in packages/core/src/baml-bridge.ts\n  // hand-mirrors the types in packages/core/baml_client/types.ts and is the\n  // only file that the project code touches.\n}\n",
  "online_assembly.baml": "// BAML schema for the user-triggered paid online assembly. This is NOT\n// invoked by the local agent loop. It is only called when the user\n// explicitly clicks \"Request Paid Online Assembly\" in the studio UI, after\n// consenting to the cost and ETA. The `user_consent: true` literal in the\n// request and the `cost_cents` / `estimated_completion_seconds` in the\n// response make the paid action explicit and auditable.\n\nclass CapabilityGap {\n  missing_capabilities string[]\n  requested_mechanic_ids string[]\n  requested_rule_ids string[]\n  requested_component_ids string[]\n  context string\n}\n\nclass PaidOnlineAssemblyRequest {\n  capability_gap CapabilityGap\n  user_consent true\n  payment_confirmation_id string\n  context_assembly_request_id string\n}\n\nclass PaidOnlineAssemblyResponse {\n  bundle_schema_version string\n  bundle_id string\n  bundle_version string\n  bundle_kind string\n  cost_cents int\n  estimated_completion_seconds int\n  remote_url string\n}\n\nfunction PaidOnlineAssembly(request: PaidOnlineAssemblyRequest) -> PaidOnlineAssemblyResponse {\n  client PaidOpenRouterLfm\n  prompt #\"\n    {{ request.capability_gap }}\n\n    {{ request.context_assembly_request_id }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}