/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AgentMessage,  AgentToolCall,  AgentToolDescriptor,  AssembleGameRequest,  AssembleGameResponse,  CapabilityGap,  PaidOnlineAssemblyRequest,  PaidOnlineAssemblyResponse } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AgentMessage {
      role?: "system" | "user" | "assistant" | "tool" | null
      content?: string | null
      tool_call_id?: string | null
      tool_name?: string | null
    }
    export interface AgentToolCall {
      call_id?: string | null
      tool_name?: string | null
      arguments?: string | null
    }
    export interface AgentToolDescriptor {
      tool_name?: string | null
      display_name?: string | null
      description?: string | null
      arguments_schema?: string | null
      capability_tags: string[]
    }
    export interface AssembleGameRequest {
      system_prompt?: string | null
      messages: AgentMessage[]
      tools: AgentToolDescriptor[]
      max_steps?: number | null
      temperature?: number | null
    }
    export interface AssembleGameResponse {
      kind?: "tool-call" | "final" | null
      message?: string | null
      tool_call?: AgentToolCall | null
    }
    export interface CapabilityGap {
      missing_capabilities: string[]
      requested_mechanic_ids: string[]
      requested_rule_ids: string[]
      requested_component_ids: string[]
      context?: string | null
    }
    export interface PaidOnlineAssemblyRequest {
      capability_gap?: CapabilityGap | null
      user_consent?: true | null
      payment_confirmation_id?: string | null
      context_assembly_request_id?: string | null
    }
    export interface PaidOnlineAssemblyResponse {
      bundle_schema_version?: string | null
      bundle_id?: string | null
      bundle_version?: string | null
      bundle_kind?: string | null
      cost_cents?: number | null
      estimated_completion_seconds?: number | null
      remote_url?: string | null
    }
}