/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AgentMessage: ClassViewer<'AgentMessage', "role" | "content" | "tool_call_id" | "tool_name">;
    
    AgentToolCall: ClassViewer<'AgentToolCall', "call_id" | "tool_name" | "arguments">;
    
    AgentToolDescriptor: ClassViewer<'AgentToolDescriptor', "tool_name" | "display_name" | "description" | "arguments_schema" | "capability_tags">;
    
    AssembleGameRequest: ClassViewer<'AssembleGameRequest', "system_prompt" | "messages" | "tools" | "max_steps" | "temperature">;
    
    AssembleGameResponse: ClassViewer<'AssembleGameResponse', "kind" | "message" | "tool_call">;
    
    CapabilityGap: ClassViewer<'CapabilityGap', "missing_capabilities" | "requested_mechanic_ids" | "requested_rule_ids" | "requested_component_ids" | "context">;
    
    PaidOnlineAssemblyRequest: ClassViewer<'PaidOnlineAssemblyRequest', "capability_gap" | "user_consent" | "payment_confirmation_id" | "context_assembly_request_id">;
    
    PaidOnlineAssemblyResponse: ClassViewer<'PaidOnlineAssemblyResponse', "bundle_schema_version" | "bundle_id" | "bundle_version" | "bundle_kind" | "cost_cents" | "estimated_completion_seconds" | "remote_url">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AgentMessage","AgentToolCall","AgentToolDescriptor","AssembleGameRequest","AssembleGameResponse","CapabilityGap","PaidOnlineAssemblyRequest","PaidOnlineAssemblyResponse",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AgentMessage = this.tb.classViewer("AgentMessage", [
          "role","content","tool_call_id","tool_name",
        ]);
        
        this.AgentToolCall = this.tb.classViewer("AgentToolCall", [
          "call_id","tool_name","arguments",
        ]);
        
        this.AgentToolDescriptor = this.tb.classViewer("AgentToolDescriptor", [
          "tool_name","display_name","description","arguments_schema","capability_tags",
        ]);
        
        this.AssembleGameRequest = this.tb.classViewer("AssembleGameRequest", [
          "system_prompt","messages","tools","max_steps","temperature",
        ]);
        
        this.AssembleGameResponse = this.tb.classViewer("AssembleGameResponse", [
          "kind","message","tool_call",
        ]);
        
        this.CapabilityGap = this.tb.classViewer("CapabilityGap", [
          "missing_capabilities","requested_mechanic_ids","requested_rule_ids","requested_component_ids","context",
        ]);
        
        this.PaidOnlineAssemblyRequest = this.tb.classViewer("PaidOnlineAssemblyRequest", [
          "capability_gap","user_consent","payment_confirmation_id","context_assembly_request_id",
        ]);
        
        this.PaidOnlineAssemblyResponse = this.tb.classViewer("PaidOnlineAssemblyResponse", [
          "bundle_schema_version","bundle_id","bundle_version","bundle_kind","cost_cents","estimated_completion_seconds","remote_url",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}