/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface AgentMessage {
  role: "system" | "user" | "assistant" | "tool"
  content: string
  tool_call_id?: string | null
  tool_name?: string | null
  
}

export interface AgentToolCall {
  call_id: string
  tool_name: string
  arguments: string
  
}

export interface AgentToolDescriptor {
  tool_name: string
  display_name: string
  description: string
  arguments_schema: string
  capability_tags: string[]
  
}

export interface AssembleGameRequest {
  system_prompt: string
  messages: AgentMessage[]
  tools: AgentToolDescriptor[]
  max_steps: number
  temperature: number
  
}

export interface AssembleGameResponse {
  kind: "tool-call" | "final"
  message?: string | null
  tool_call?: AgentToolCall | null
  
}

export interface CapabilityGap {
  missing_capabilities: string[]
  requested_mechanic_ids: string[]
  requested_rule_ids: string[]
  requested_component_ids: string[]
  context: string
  
}

export interface PaidOnlineAssemblyRequest {
  capability_gap: CapabilityGap
  user_consent: true
  payment_confirmation_id: string
  context_assembly_request_id: string
  
}

export interface PaidOnlineAssemblyResponse {
  bundle_schema_version: string
  bundle_id: string
  bundle_version: string
  bundle_kind: string
  cost_cents: number
  estimated_completion_seconds: number
  remote_url: string
  
}
